#!/usr/bin/env python3
"""Generate port/shader_selftest_cases.inc: every combiner mode pair the game uses.

The self-test (port/ShaderSelfTest.cpp, PAPERSHIP_SHADER_SELFTEST=1) renders a
triangle with each pair under several render modes so every shader variant the
game can request is compiled through libultraship's GLSL/GLSL ES generator.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CALL = re.compile(r"g[s]?DPSetCombineMode\(\s*(?:[A-Za-z_][\w>.()\-]*\+\+\s*,\s*)?([A-Za-z_]\w*)\s*,\s*([A-Za-z_]\w*)\s*\)")


DEFINE = re.compile(r"^[ \t]*#[ \t]*define[ \t]+((?:G_CC_|PM_CC)\w*)[ \t]+([^\n]*?)\s*$", re.M)


def main() -> int:
    pairs = set()
    local_defines = {}  # combiner macros defined in .c files rather than headers
    for path in list((ROOT / "src").rglob("*.c")) + list((ROOT / "include").rglob("*.h")):
        text = path.read_text(errors="replace")
        for a, b in CALL.findall(text):
            if a.startswith(("G_CC_", "PM_CC")) and b.startswith(("G_CC_", "PM_CC")):
                pairs.add((a, b))
        if path.suffix == ".c":
            for name, body in DEFINE.findall(text):
                local_defines.setdefault(name, body.split("//")[0].strip())
    used = {name for pair in pairs for name in pair}
    out = ROOT / "port" / "shader_selftest_cases.inc"
    lines = ["// Generated by tools/port/gen_shader_selftest.py - do not edit.",
             "// One entry per gDPSetCombineMode() argument pair found in src/ and include/."]
    for name in sorted(used & set(local_defines)):
        # Defined in a .c file, so it is not visible through the headers; repeat it here.
        lines += [f"#ifndef {name}", f"#define {name} {local_defines[name]}", "#endif"]
    lines.append("#define SHADER_SELFTEST_CASES(X) \\")
    for a, b in sorted(pairs):
        lines.append(f'    X("{a}, {b}", {a}, {b}) \\')
    lines.append("    /* end */")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} with {len(pairs)} combiner pairs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
